# Generated by Django 2.2 on 2019-10-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='Password',
        ),
    ]
